alias deit='docker exec -it'
alias dils='docker image ls'
alias dirm='docker image rm'
alias dips='docker image ps'
alias dcps='docker container ps'
alias dcpsa='docker container ps -a'
alias dl='docker logs'
