alias ga='git add'
alias gb='git branch'
alias gba='git branch -a'
alias gbd='git branch -d'
alias gcm='git commit -m'
alias gd='git diff'
alias gdc='git diff --cached'
alias gfa='git fetch --all'
alias gl='git log'
alias gl1="git log --pretty='format:%C(yellow)%h %C(green)%cd %C(reset)%s %C(red)%d %C(cyan)[%an]' --date=iso"
alias grhh='git reset --hard HEAD'
alias grsh='git reset --soft HEAD'
alias grs='git restore --staged'
alias grv='git remote -v'
alias gs='git status'
alias gsw='git switch'
alias gsw-='git switch -'
alias gswc='git switch -c'
alias gtn='git tag -n'

